parameters:
    idfm.api_key: '%env(IDFM_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\ImportTransportDataCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\TrafficService:
        arguments:
            $apiKey: '%idfm.api_key%'